### ISSUE TITLE
Don't clear event queue if an event fails

### ISSUE THREAD

**Issue by timofurrer** [pytransitions/transitions#224] opened 2017-06-06 08:59 UTC
Here https://github.com/tyarkoni/transitions/blob/master/transitions/core.py#L857 the entire event queue is cleared if an attempt to transition to another state somehow failed. 

This especially bothers me for the `MachineError` exception e.g. raised here: https://github.com/tyarkoni/transitions/blob/master/transitions/core.py#L303

I have the following scenarios where I use a queued state machine:

1. Set machine to state `preparing`
2. Set machine to state `request_abort` -> because an after hook is still running from the `preparing` transition this event gets queued
3. The `preparing` transition after hook finished and the `request_abort` transition event is consumed from the event queue
4. The thread which did `1.` attempts a transition to state `ready` which is only possible if in state `preparing` but the state machine is in state `request_abort` because of `3.` This action fails with the above mentioned `MachineError`
5. In the meantime the `request_abort` after hook has queued a `abort` transition event
6. **but** this `abort` transition was cleared because of `MachineError`

That's a pretty high-level description but I hope it helps.

Is there something completely conceptionally wrong with my state machine (from what you can tell) or would it be possible to support that for a specific transition these MachineError exceptions are disabled? I know about `ignore_invalid_triggers` but that's only possible on state or machine level but not transition, right?

**Comment by timofurrer** [comment] 2017-06-06 09:07
What I did to prevent this `MachineError` was to set `unless`-guards for a transition. However, because this guards are checked after the `MachineError` is raised (due to no valid transition with this source state) I had to allow those missing source states - but they can never be trigger because the unless guards prevent it.

Something like this, which is quite ugly..

```python
self.state_machine.add_transition('prepared', ['preparing', 'request_abort'], 
    'ready', unless=[self.is_request_abort])
```

**Comment by aleneum** [comment] 2017-06-07 07:00
Hi @timofurrer,

As  you mentioned already, `MachineError` for invalid transitions can be omitted by `ignore_invalid_triggers` in cases where this kind of transitions is part of the workflow.
If set to `True`, no Error will be raised and the processing of the queue will continue.
However, you cannot set this option for transitions individually.

Imho, clearing the event queue is quite vital for cases in which `MachineError` actually indicates issues with the ongoing queue processing.

Could you elaborate why `ignore_invalid_triggers` is not sufficient for you?

**Comment by timofurrer** [comment] 2017-06-07 07:11
> Imho, clearing the event queue is quite vital for cases in which MachineError actually indicates issues with the ongoing queue processing.

In most cases that's probably true.

> Could you elaborate why ignore_invalid_triggers is not sufficient for you?

It's not sufficient in my case because I only want to ignore invalid triggers if the event was triggered from a certain to a certain state. And not always to a certain state.

What I did as a work around was (what I've already mentioned in the second post) to include the source state I want to ignore in a transition but specify the `unless`-guard so that this transition from this source state basically is never triggered - which is pretty ugly. With that the transition is simply prevented by the guard and no `MachineError` is raised - so the queue remains as is.

**Comment by aleneum** [comment] 2017-06-07 08:11
Okay, let me reformulate, why do you need errors to be raised in every other case except that?

**Comment by aleneum** [comment] 2017-06-08 07:15
Another follow up:

the state logic for your presented case becomes much easier if you can timeout the blocking call in `after` directly. Your code could look something like this then:

```python
class Model(object):
    def send_request(self):
        try:
           # call the blocking function with timeout parameter, if possible
            module.blocking_call(..., timeout=1)
            self.ready()
        # catch the module's timeout error
        except module.Timeout:
            self.timeout()


states = ['preparing', 'request_abort', 'ready']
transitions = [{'trigger': 'query', 'source': 'ready', 'dest': 'preparing', 'after': 'send_request',
               ['ready', 'preparing', 'ready'],
               ['timeout', 'preparing', 'request_abort']]

model = Model()
m = Machine(model, states= states, transitions=transitions)
m.query()
```

**Comment by aleneum** [comment] 2017-06-20 20:33
Since there has been activity for 14 days I will close this issue for now. Feel free to reopen it if the issue is still present or you want to provide new insights.

**Closed by aleneum** 2017-06-20 20:33 UTC
