### ISSUE TITLE
The Event and Machine have cyclic dependency.

### ISSUE THREAD

**Issue by yw94** [pytransitions/transitions#642] opened 2023-11-06 13:29 UTC
Thank you for taking the time to report a bug! Your support is essential for the maintenance of this project. Please fill out the following fields to ease bug hunting and resolving this issue as soon as possible:

**Describe the bug**
Cyclic dependency exists between the machine and event, causing memory overflow.

**Minimal working example**

```python
class Foo:

    def __init__(self):
        self.machine = Machine(
            model=self, 
            states=["a", "b"], 
            transitions=[{"trigger": "a_to_b", "source": "a", "dest": "b"}], 
            initial="a"
        )
```

**Expected behavior**
The debugging result shows that the machine.events contains the event instance, the event instance has the machine attribute, and cyclic dependency.

**Additional context**

**Comment by aleneum** [comment] 2023-11-06 15:50
When I prevent garbage collection like this:

```python
# ...
counter = 0
events = []
with open("memory.csv", "w") as f:
    while True:
        counter += 1
        foo = Foo()
        events.append(foo.machine.events["a_to_b"])  # <-- keep reference to an event and thus to machine
        if counter % 50000 == 0:
            print(f"{counter},{process.memory_info().rss}", file=f)
            f.flush()
# ...
```

the memory consumption increases rather fast:

![Screenshot 2023-11-06 at 16 45 58](https://github.com/pytransitions/transitions/assets/205986/3d07e854-e92f-44ca-b4a4-04a12511158e)

At 1.4 million instances, the process already consume almost 12 billion bytes (12 GB).

**Comment by aleneum** [comment] 2023-11-10 17:17
@yw94: I will close this issue since I cannot verify a memory leak caused by `transition` with information I currently have. Feel free to comment anyway if your problem persists.

**Closed by aleneum** 2023-11-10 17:17 UTC
Labels: bug
