### ISSUE TITLE
Machine for multi-threading

### ISSUE THREAD

**Issue by timofurrer** [pytransitions/transitions#225] opened 2017-06-06 13:10 UTC
I'm considering using `transitions` for a rather big multi-threaded application. I've had a look at the `queue`-feature of the `Machine` and the `LockedMachine` and those in combination. 

However, it doesn't fit my needs so far. The `LockedMachine` doesn't fit for me because sometimes I'm doing rather long-ish actions in a transitions `after`-hook and during that time the state machine is completely locked by [locking.py#L130](https://github.com/tyarkoni/transitions/blob/master/transitions/extensions/locking.py#L130). Thus, all calls to any method is blocked - calls like `is_<somestate>()` etc. which don't have to be locked.

I really like the idea of the transition event queue. However, that's not really thread-safe to use without the `LockedMachine`. 

Do you see any possibility that we could add a lock around [core.py#L847](https://github.com/tyarkoni/transitions/blob/master/transitions/core.py#L847) and [core.py#851](https://github.com/tyarkoni/transitions/blob/master/transitions/core.py#L851)? (and if necessary in the `while` as well - didn't dig to much into it yet)
Would that be sufficient for a thread-safe queued state machine? As far as I've understood we don't have to lock all the other methods because only one state at the time can be processed due to the above mentioned locks?

But as I've said I'm not too familiar with the current implementation thus my solution proposals maybe complete non-sense - you might correct me ;)

Thanks!

**Comment by aleneum** [comment] 2017-06-07 08:02
Hi @timofurrer,

> Thus, all calls to any method is blocked - calls like is_<somestate>() etc. which don't have to be locked.

This is intentional since a transition is currently processed and the machine is in an undefined state. Even though the models state has already been changed, `after` and `finalize` may alter the state again.
If `is_stated<>` would not be locked, this might trigger actions which are invalid the moment they are triggered. This will be an even bigger problem if you use multiple models and racing conditions become more frequent.

> Do you see any possibility that we could add a lock around core.py...

Sorry, but no. We strive for a  basic machine which is lightweight and fits general purposes. Locking involves an overhead which may not be in the best interest of most library users. This estimation may be wrong though. If this issue is flooded with opposing feedback, I will gladly change my mind.

> But as I've said I'm not too familiar with the current implementation thus my solution proposals maybe complete non-sense [...]

Feedback is always appreciated and we of course try to improve `transitions` to support all the use cases around. However, my following conceptional suggestions might be non-sense since I do not know what you are actually planning to achieve:

1. reduce threaded access to the state machine whenever possible: This is what I have been told from our robotics department and I believe them since they work with quite complex state machines on a daily bases. I personally work with some sensor-event-based multithreaded state machines and trying to decouple state transition and state behaviour left me with less complex and easier to debug code.

2. detach `after` from the blocking process: If your `after` callback is blocking and you consider the state transition finished, it might be a good idea to dispatch the blocking process to a new worker thread.

3. queueing transitions which become invalid during the queue processing could be avoided maybe: Since you are using threads quite a lot you are probably waiting for data from somewhere to trigger certain actions. I have had good experience with applying sensor readings and callbacks to the model. The state machine thread only evaluates the model and triggers transitions whenever suitable. This leads to a very responsive state machine and less interference caused by parallel resource access. This is basically suggestion 1 in disguise.

Again, these are just suggestions and might not fit your use case.

**Comment by aleneum** [comment] 2017-06-20 20:32
Since there has been no follow up for 14 days I will close this issue for now. Feel free to reopen it if the issue is still present or you want to provide new insights.

**Closed by aleneum** 2017-06-20 20:32 UTC
