### ISSUE TITLE
timeouts: initial state does not run its timeout the first time

### ISSUE THREAD

**Issue by xavigisbeg** [pytransitions/transitions#285] opened 2018-01-26 14:10 UTC
First of all, let me thank you for your great documentation, I think I haven't seen any other package so well explained with examples for those who aren't pros.

### The problem
I have been following your examples and tried to implement a test script of my own with the timeouts. They run well, but **having a timeout on the initial state causes it not to be run the first time**. 

If I run after the instantiation `.to_...()` to it or the FSM flow enters this state later, the timeout executes well. I guess the timeout object will be set after the machine sets the first state, so it does not see a transition. But I haven't gone through all the transitions code and don't understand it.

### What can be done
This can easily be managed by either starting from a void state that immediately goes to the regular state used before to initialize, that has a timeout. Or to have it `.to_...()` to the initial state just after the machine instantiation. 

Maybe you can work this out so that the timeout is considered the first time, or if it's too much trouble you can add a short info about this in the Timeout part of the documentation so we can avoid possible misbehaviors

**Comment by aleneum** [comment] 2018-01-29 09:32
Hello @xavigisbeg,

timeouts are initialised when a state is entered. However, an initial state is actually not entered but just set. Figuratively speaking, the model 'spawns' in this state. This -- the spawning part -- is intended behaviour and required for situations where machines are (re)initiated occasionally.

The Readme also mentions that:

> Note that on_enter_«state name» callback will not fire when a Machine is first initialized. For example if you have an on_enter_A() callback defined, and initialize the Machine with initial='A', on_enter_A() will not be fired until the next time you enter state A.

Your solution of having a preparation or init state before your actual first state is the most common approach for triggering `enter` callbacks for the intended first state. You could also have a reflexive transition for your first state to minimize the logic overhead:

```python
m = Machine(states=['A'], transitions=[['init', 'A', 'A']], initial='A')
m.init()
```

Since no state callback is triggered during the 'spawn process' there is no way I can think of which deals with this case elegantly.  If you come up with a generic solution, let me know. For now, I will close this issue.

**Closed by aleneum** 2018-01-29 09:32 UTC

**Comment by xavigisbeg** [comment] 2018-01-29 11:10
Thanks for the clarification @aleneum!
