### ISSUE TITLE
Conditions on nested state machines don't get called properly

### ISSUE THREAD

**Issue by translunar** [pytransitions/transitions#595] opened 2022-11-21 19:15 UTC
**Describe the bug**
When I define a machine with

```python
states=[{"name": "A"}, {"children", child.machine}]
```
and the `child` model defines a transition with `"conditions": "test"`, it attempts to call `test()` on the parent model rather than the nested model.

**Minimal working example**

```python
import unittest

from transitions.extensions import MachineFactory

class Parent(object):
    def __init__(self, child):
        states = [
            { "name": "A" },
            { "name": "B", "children": child.machine }
        ]

        transitions = [
            {"trigger": "go", "source": "A", "dest": "B_a"},
            {"trigger": "go", "source": "B_b", "dest": "A"},
        ]

        machine_cls = MachineFactory.get_predefined(nested=True)
        self.machine = machine_cls(
            model=self,
            states=states,
            transitions=transitions,
            initial="A"
        )
        self.test_called = False

    def test(self):
        self.test_called = True

class Child(object):
    def __init__(self):
        states = [
            {"name": "a"},
            {"name": "b"},
        ]

        transitions = [
            {"trigger": "go", "source": "a", "dest": "b", "conditions": "test"}
        ]

        machine_cls = MachineFactory.get_predefined(nested=True)
        self.machine = machine_cls(model=self, states=states, transitions=transitions)
        self.test_called = False

    def test(self):
        self.test_called = True

class TestNestedModel(unittest.TestCase):

    def test_mwe(self):
        c = Child()
        p = Parent(c)

        assert p.test_called == False
        assert c.test_called == False

        p.go()

        assert p.test_called == False
        assert c.test_called == False

        p.go()

        assert c.test_called == True
        assert p.test_called == False
        
```

**Expected behavior**
I expect `test()` to get called on the child model and not the parent model.

**Additional context**

**Comment by translunar** [comment] 2022-11-21 19:46
I found a workaround, which is to refer to the function by reference instead of by string, e.g. `"conditions": self.test`.

**Comment by aleneum** [comment] 2022-11-22 07:56
Hello @translunar,

as of now this is intended behaviour. The documentation mentions

> (Nested)State instances are just referenced which means changes in one machine's collection of states and events will influence the other machine instance. **Models and their state will not be shared though**.

Strings as callbacks will always be treated as methods assigned to the currently processed model. You could either use inheritance or reference methods directly (as you just did).

**Closed by aleneum** 2022-11-22 07:56 UTC
Labels: bug

**Comment by translunar** [comment] 2022-11-22 23:55
It might be helpful to clarify this in the documentation. I had to dig through the issues to find it.
