### ISSUE TITLE
Problem extending Machine

### ISSUE THREAD

**Issue by mrtvon** [pytransitions/transitions#260] opened 2017-10-10 12:38 UTC
I am using Transitions as a core component in an application framework. To make life easy for the users of this framework I want to provide a base FSM with core states/transitions, and a simple way for them to extend it.

In trying to do this, I used inheritance to subclass Machine and decorate it with the base FSM, however I noticed that the derived object cannot be garbage collected. The same is also true if composition is used and the model is the parent class instance.

This is my test code using inheritance (apologies, markdown isn't working well for my code):

```python
import gc

from transitions import State, Machine

class MyMachine(Machine):
    def __init__(self):
        Machine.__init__(self)

    def __del__(self):
        pass
        #not called

def create():
    m = MyMachine()
    print gc.get_referrers(m)
    print gc.get_referents(m)

if __name__ == "__main__":
    create()
```

The gc output is as follows:

```
[ < frame object at 0x7f791d4893c0 > , [ < __main__.MyMachine object at 0x7f791cea1f90 > ], {
	'machine': < __main__.MyMachine object at 0x7f791cea1f90 > ,
	'transitions': defaultdict( < type 'list' > , {
		'initial': [ < Transition('initial', 'initial') @140158152954256 > ]
	}),
	'name': 'to_initial'
}, ( < __main__.MyMachine object at 0x7f791cea1f90 > , ), 
   ( < __main__.MyMachine object at 0x7f791cea1f90 > , ), 
	< bound method MyMachine.is_state of < __main__.MyMachine object at 0x7f791cea1f90 >> , 
('initial', < __main__.MyMachine object at 0x7f791cea1f90 > )]



[{
	'_initial': 'initial',
	'_transition_queue': deque([]),
	'name': '',
	'trigger': < functools.partial object at 0x7f791ceabaf8 > ,
	'_prepare_event': [],
	'models': [ < __main__.MyMachine object at 0x7f791cea1f90 > ],
	'send_event': False,
	'to_initial': < functools.partial object at 0x7f791ceabb50 > ,
	'_before_state_change': [],
	'states': OrderedDict([('initial', < State('initial') @140158152954064 > )]),
	'state': 'initial',
	'_queued': False,
	'auto_transitions': True,
	'ignore_invalid_triggers': None,
	'_after_state_change': [],
	'is_initial': < functools.partial object at 0x7f791ceabba8 > ,
	'events': {
		'to_initial': < Event('to_initial') @140158152954128 >
	},
	'_finalize_event': []
}, < class '__main__.MyMachine' > ]
```

**Comment by mrtvon** [comment] 2017-10-10 15:40
OK so it seems one part of the problem is the hard reference to "machine" in Event, looks like this can be quite easily solved with weakref.

The second part of the problem seems to be the decorating of the model in Machine.add_model

Is this a know issue, or does it indicate design intent?

**Comment by aleneum** [comment] 2017-10-11 07:36
Hello @mrtvon,

> The second part of the problem seems to be the decorating of the model in Machine.add_model

I guess this is where most of your garbage collection issues arise. Models keep references to machines through the added convenience functions. This is indeed intended by design. Currently, `transitions` contains no feature to remove these functions again. One of the reasons is that it would take some introspection to determine if a function has been added by a machine or not (e.g. a model will not be extended with a `trigger` method in case it already contains a method called like this)

> OK so it seems one part of the problem is the hard reference to "machine" in Event, looks like this can be quite easily solved with weakref.

This seems to be a symptom of the previously mentioned issue. A machine has a list of events but also assigns the even triggers to model attributes.

If this coupling is not desired you can skip adding models to machine and call `Event.trigger` directly:

```python
import gc
from transitions import Machine


class Model(object):
    def __init__(self, state):
        self.state = state

    def enter_state(self):
        print("State entered!")


def create():
    machine = Machine(model=None, states=['A', 'B'], initial='A', after_state_change='enter_state')
    model = Model(machine.initial)
    print(gc.get_referents(model))  # [{'state': 'A'}, <class '__main__.Model'>]
    machine.events['to_B'].trigger(model=model)  # State entered!
    print(model.state)  # B


create()
```
You just have to make sure that you model contains a `state` string attribute and always call trigger with the appropriate model. You see that even though the machine was initialised without a model, it will call the callback of the passed model as callback strings are resolved during event processing.

If you are willing to override `__getattribute__` you can achieve the almost the same behaviour/convenience like adding models to machine instances:

```python
class Model(object):

    def __getattribute__(self, item):
        try:
            return super(Model, self).__getattribute__(item)
        except AttributeError:
            if item in self.machine.events:
                return partial(self.machine.events[item].trigger, self)
            raise

model.to_B()
```

**Comment by mrtvon** [comment] 2017-10-11 14:56
Thank you, the above approach achieves exactly what I need, though for my solution I do need to apply the override.

**Comment by aleneum** [comment] 2017-10-16 09:52
> though for my solution I do need to apply the override.

This shouldn't be an issue. If it is, feel free to report back. Closing this for now.

**Closed by aleneum** 2017-10-16 09:52 UTC
