### ISSUE TITLE
Issues with the `EventData` object being sent to the callback functions

### ISSUE THREAD

**Issue by parthsharma1996** [pytransitions/transitions#350] opened 2019-05-13 11:00 UTC
I have two issues with the `EventData` object being sent to the callback functions:

For most part of our project we didn't really need any event related details like the trigger, transition etc in the callback functions. Hence we do not have the argument `event_data` in any of our callback function definitions. 
Now we've hit a requirement in which a `prepare_event` function needs the destination associated with the currently undergoing transition. 

To implement this currently we'll have to change the function definitions of all of our callback functions, while only a couple of them will actually use this information. 
Is there a way to get this information using some internal (`self.xyz`) variable instead of passing the `event_data` function? 

Secondly, in the `event_data` object being passed to the `prepare_event` functions, the `.transition` attribute is `None` because apparently they are only set before the execution of a transition which is attributed to this code (Line 403 onwards in `core.py`)

    def _process(self, event_data):
        for func in self.machine.prepare_event:
            self.machine.callback(func, event_data)
            _LOGGER.debug("Executed machine preparation callback '%s' before conditions.", func)

        try:
            for trans in self.transitions[event_data.state.name]:
                event_data.transition = trans
                if trans.execute(event_data):
                    event_data.result = True
                    break

1. Can you explain why this is the case and why aren't the `prepare_event` functions being called before instead of being called with each transition? 

Our use-case requires a `prepare_event` function to know the `dest` attribute of the currently  undergoing transition. Is that possible?

**Comment by aleneum** [comment] 2019-08-13 14:19
Hi @parthsharma1996,

sorry for the late reply.

> Can you explain why this is the case and why aren't the prepare_event functions being called before instead of being called with each transition?

Have a look at the documentation. We have two prepare callbacks:


|      Callback                  | Current State |               Comments                                      |
|--------------------------------|:-------------:|-------------------------------------------------------------|
| `'machine.prepare_event'`      | `source`      | executed *once* before individual transitions are processed |
| `'transition.prepare'`         | `source`      | executed as soon as the transition starts                   |
| `'transition.conditions'`      | `source`      | conditions *may* fail and halt the transition               |
| `'transition.unless'`          | `source`      | conditions *may* fail and halt the transition               |

 `prepare_event` is called *once* for each event by design. At this point it is not yet known which transition (if any) will be evaluated. Transition objects have another `prepare` callback which is called more or less as soon as `Transition.execute` is called. 

> Our use-case requires a prepare_event function to know the dest attribute of the currently undergoing transition. Is that possible?

You should bind your callbacks to every transition's `prepare` hook. This way, it is called for each evaluated transition individually.

**Comment by aleneum** [comment] 2019-08-27 10:46
I close this issue since their has not been any feedback in 14 days. Feel free to comment if this still is an issue for you. I will reopen the issue if required.

**Closed by aleneum** 2019-08-27 10:46 UTC
